/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejestracja nowego użytkownika
         * @description Celowy brak walidacji siły hasła.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRequest"];
                };
            };
            responses: {
                /** @description Użytkownik zarejestrowany pomyślnie */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Błąd walidacji (np. email zajęty) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logowanie użytkownika
         * @description Zwraca token JWT. **Podatność:** Celowy brak rate-limitingu (podatne na brute-force).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRequest"];
                };
            };
            responses: {
                /** @description Pomyślne logowanie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Nieprawidłowe dane logowania */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pobiera listę produktów
         * @description Parametr `search` musi być bezpośrednio wklejany do zapytania SQL na backendzie (np. `SELECT * FROM products WHERE name LIKE '%${search}%'`). W przypadku błędu składni SQL, serwer powinien zwrócić błąd 500 z pełnym stack trace.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Szukana fraza w nazwie produktu */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista produktów */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobiera szczegóły pojedynczego produktu */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID produktu */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Szczegóły produktu */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                /** @description Nie znaleziono produktu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pobiera opinie o produkcie
         * @description Ważne dla Frontendu Zwracane dane content mogą zawierać złośliwy kod HTML/JS. Frontend musi to wyrenderować używając np. `dangerouslySetInnerHTML`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID produktu */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista opinii */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Dodaje opinię do produktu
         * @description Podatność (Stored XSS) Backend absolutnie nie może filtrować ani sanityzować pola `content` w locie do bazy danych. Tagi `<script>` muszą być zapisane w oryginalnej formie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID produktu */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Świetny produkt! <script>alert(localStorage.getItem('token'))</script> */
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Opinia dodana */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Brak lub nieprawidłowy token JWT */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Składa nowe zamówienie
         * @description Podatność (Hardcoded Secrets) Kontroler obsługujący ten endpoint musi zawierać w kodzie zahardkodowany, fikcyjny klucz API do procesora płatności.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderRequest"];
                };
            };
            responses: {
                /** @description Zamówienie utworzone */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pobiera szczegóły zamówienia
         * @description Podatność (IDOR) Backend weryfikuje jedynie ważność tokenu JWT, ale NIE sprawdza, czy `user_id` przypisane do zamówienia zgadza się z ID w tokenie. Pozwala to na podglądanie cudzych koszyków poprzez zmianę `id` w URL.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID zamówienia */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Szczegóły zamówienia */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Nie znaleziono zamówienia */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthRequest: {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example supertajne123 */
            password: string;
        };
        AuthResponse: {
            /** @description JWT Bearer token */
            token?: string;
        };
        Product: {
            /** @example 1 */
            id?: number;
            /** @example Kubek Programisty */
            name?: string;
            /** @example Ogrzewa dłonie i kompiluje kod */
            description?: string;
            /**
             * Format: float
             * @example 49.99
             */
            price?: number;
        };
        Review: {
            id?: number;
            product_id?: number;
            /** @description Zwracany mail użytkownika, który napisał opinię */
            user_email?: string;
            /** @description Treść opinii, potencjalnie złośliwa (XSS) */
            content?: string;
        };
        OrderRequest: {
            /**
             * @example [
             *       1,
             *       2,
             *       5
             *     ]
             */
            product_ids: number[];
        };
        Order: {
            id?: number;
            /** @description ID użytkownika - przydatne do weryfikacji luki IDOR */
            user_id?: number;
            /** Format: float */
            total?: number;
            /** @example PAID */
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
