name: Phase 1 CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image - Backend
        run: |
          docker build -t ghcr.io/becyb-team-15/devshop-backend:${{ github.sha }} ./devshop-backend
          docker push ghcr.io/becyb-team-15/devshop-backend:${{ github.sha }}

      - name: Build and push image - Frontend
        run: |
          docker build -t ghcr.io/becyb-team-15/devshop-frontend:${{ github.sha }} ./devshop-frontend
          docker push ghcr.io/becyb-team-15/devshop-frontend:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          (Get-Content k8s/backend-deployment.yaml) -replace 'image: ghcr.io/becyb-team-15/devshop-backend:latest', 'image: ghcr.io/becyb-team-15/devshop-backend:${{ github.sha }}' | Set-Content k8s/backend-deployment.yaml
          (Get-Content k8s/frontend-deployment.yaml) -replace 'image: ghcr.io/becyb-team-15/devshop-frontend:latest', 'image: ghcr.io/becyb-team-15/devshop-frontend:${{ github.sha }}' | Set-Content k8s/frontend-deployment.yaml

          kubectl apply -f k8s/01-namespace.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml